name: Build data.json

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Run yamllint
        uses: bewuethr/yamllint-action@v1
        with:
          config-file: .github/workflows/yamlconfig
        continue-on-error: false

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Create Json
        run: npm run compile

      - name: Update main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: staging
          commit_message: generate Json
          commit_options: '--no-verify --signoff'
          repository: .
          add_options: '-u'
          push_options: '--force'
          skip_dirty_check: false
            
      - name: Trigger Staging Server to fetch
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://wwwtest.digitale-gesellschaft.ch/auskunftsbegehren/deploy/deploy.php?key=${{ secrets.STAGING_DEPLOYKEY }}'
          method: 'GET'
          username: admin
          password: ${{ secrets.STAGING_WWWTEST_PASSWORD }}
