name: Build data.json

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Check out code
        uses: actions/checkout@main
      - name: Run yamllint
        uses: bewuethr/yamllint-action@v1
        with:
          config-file: .github/workflows/yamlconfig
        continue-on-error: false

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install

      - name: Create Json
        run: npm run compile
